import React, { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Switch } from '@/components/ui/switch';
import { Badge } from '@/components/ui/badge';
import { Minus, Plus, Loader2, Calendar, Clock, MapPin, Timer, Shuffle, RotateCcw, Layers, Crown } from 'lucide-react';
import { SessionType } from '../backend';

// SessionConfigForm only deals with the user-visible fields.
// sessionCode is generated by the caller (CreateSession page).
export interface SessionConfigFormFields {
  courts: number;
  date?: string;
  time?: string;
  venue?: string;
  duration?: number;
  sessionType: SessionType;
  isRanked: boolean;
}

interface SessionConfigFormProps {
  onSubmit: (params: SessionConfigFormFields) => void | Promise<void>;
  isLoading?: boolean;
  submitLabel?: string;
}

interface GameTypeOption {
  value: SessionType;
  label: string;
  description: string;
  icon: React.ReactNode;
}

const GAME_TYPE_OPTIONS: GameTypeOption[] = [
  {
    value: SessionType.randomAllotment,
    label: 'Random Allotment',
    description: 'Players randomly assigned to courts each round',
    icon: <Shuffle className="h-4 w-4" />,
  },
  {
    value: SessionType.roundRobin,
    label: 'Round Robin',
    description: 'Every player faces every other player',
    icon: <RotateCcw className="h-4 w-4" />,
  },
  {
    value: SessionType.ladderLeague,
    label: 'Ladder League',
    description: 'Players move up or down based on results',
    icon: <Layers className="h-4 w-4" />,
  },
  {
    value: SessionType.kingQueenOfTheCourt,
    label: 'King/Queen of the Court',
    description: 'Winners stay on, losers rotate off',
    icon: <Crown className="h-4 w-4" />,
  },
];

export default function SessionConfigForm({
  onSubmit,
  isLoading = false,
  submitLabel = 'Create Game',
}: SessionConfigFormProps) {
  const [courts, setCourts] = useState(2);
  const [date, setDate] = useState('');
  const [time, setTime] = useState('');
  const [venue, setVenue] = useState('');
  const [duration, setDuration] = useState('');
  const [sessionType, setSessionType] = useState<SessionType>(SessionType.randomAllotment);
  const [isRanked, setIsRanked] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (isLoading) return;
    await onSubmit({
      courts,
      date: date || undefined,
      time: time || undefined,
      venue: venue.trim() || undefined,
      duration: duration ? parseInt(duration, 10) : undefined,
      sessionType,
      isRanked,
    });
  };

  const decrementCourts = () => setCourts((prev) => Math.max(1, prev - 1));
  const incrementCourts = () => setCourts((prev) => Math.min(10, prev + 1));

  return (
    <Card className="shadow-card">
      <CardHeader>
        <CardTitle className="font-display">Game Configuration</CardTitle>
        <CardDescription>Set up your pickleball game details</CardDescription>
      </CardHeader>
      <CardContent>
        <form onSubmit={handleSubmit} className="space-y-6">
          {/* Game Type Selector */}
          <div className="space-y-3">
            <label className="text-sm font-medium text-foreground">
              Game Type <span className="text-destructive">*</span>
            </label>
            <div className="grid grid-cols-1 gap-2">
              {GAME_TYPE_OPTIONS.map((option) => {
                const isSelected = sessionType === option.value;
                return (
                  <button
                    key={option.value}
                    type="button"
                    onClick={() => setSessionType(option.value)}
                    disabled={isLoading}
                    className={`flex items-center gap-3 p-3 rounded-xl border-2 text-left transition-all ${
                      isSelected
                        ? 'border-primary bg-primary/10 text-foreground'
                        : 'border-border bg-background hover:border-primary/40 hover:bg-muted/40 text-foreground'
                    }`}
                  >
                    <div
                      className={`flex-shrink-0 w-8 h-8 rounded-lg flex items-center justify-center ${
                        isSelected ? 'bg-primary text-primary-foreground' : 'bg-muted text-muted-foreground'
                      }`}
                    >
                      {option.icon}
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2">
                        <span className="text-sm font-semibold">{option.label}</span>
                        {isSelected && (
                          <Badge className="text-[10px] px-1.5 py-0 h-4">Selected</Badge>
                        )}
                      </div>
                      <p className="text-xs text-muted-foreground mt-0.5 leading-tight">
                        {option.description}
                      </p>
                    </div>
                  </button>
                );
              })}
            </div>
          </div>

          {/* Ranked / Unranked Toggle */}
          <div className="space-y-2 border-t border-border pt-4">
            <div className="flex items-center justify-between">
              <div className="space-y-0.5">
                <label className="text-sm font-medium text-foreground flex items-center gap-2">
                  Ranked Game
                  <Badge
                    variant={isRanked ? 'default' : 'secondary'}
                    className="text-[10px] px-1.5 py-0 h-4"
                  >
                    {isRanked ? 'Ranked' : 'Unranked'}
                  </Badge>
                </label>
                <p className="text-xs text-muted-foreground">
                  {isRanked
                    ? 'Scores will be recorded and player ratings updated after each round'
                    : 'Casual play — no ratings affected'}
                </p>
              </div>
              <Switch
                checked={isRanked}
                onCheckedChange={setIsRanked}
                disabled={isLoading}
                aria-label="Toggle ranked game"
              />
            </div>
          </div>

          {/* Courts Stepper */}
          <div className="space-y-3 border-t border-border pt-4">
            <label className="text-sm font-medium text-foreground">
              Number of Courts
            </label>
            <div className="flex items-center justify-center gap-6">
              <Button
                type="button"
                variant="outline"
                size="icon"
                onClick={decrementCourts}
                disabled={courts <= 1 || isLoading}
                className="h-12 w-12 rounded-full"
                aria-label="Decrease courts"
              >
                <Minus className="h-5 w-5" />
              </Button>
              <div className="flex flex-col items-center">
                <span className="text-5xl font-bold font-display text-primary leading-none">
                  {courts}
                </span>
                <span className="text-xs text-muted-foreground mt-1">
                  {courts === 1 ? 'court' : 'courts'}
                </span>
              </div>
              <Button
                type="button"
                variant="outline"
                size="icon"
                onClick={incrementCourts}
                disabled={courts >= 10 || isLoading}
                className="h-12 w-12 rounded-full"
                aria-label="Increase courts"
              >
                <Plus className="h-5 w-5" />
              </Button>
            </div>
            <p className="text-xs text-muted-foreground text-center">
              Each court supports 4 players (2 vs 2)
            </p>
          </div>

          {/* Game Details */}
          <div className="space-y-4 border-t border-border pt-4">
            <p className="text-sm font-medium text-foreground">
              Game Details <span className="text-muted-foreground font-normal">(optional)</span>
            </p>

            <div className="grid grid-cols-2 gap-3">
              {/* Date */}
              <div className="space-y-1.5">
                <Label htmlFor="game-date" className="text-xs flex items-center gap-1.5 text-muted-foreground">
                  <Calendar className="h-3.5 w-3.5" /> Date
                </Label>
                <Input
                  id="game-date"
                  type="date"
                  value={date}
                  onChange={(e) => setDate(e.target.value)}
                  disabled={isLoading}
                  className="text-sm"
                />
              </div>

              {/* Time */}
              <div className="space-y-1.5">
                <Label htmlFor="game-time" className="text-xs flex items-center gap-1.5 text-muted-foreground">
                  <Clock className="h-3.5 w-3.5" /> Time
                </Label>
                <Input
                  id="game-time"
                  type="time"
                  value={time}
                  onChange={(e) => setTime(e.target.value)}
                  disabled={isLoading}
                  className="text-sm"
                />
              </div>
            </div>

            {/* Venue */}
            <div className="space-y-1.5">
              <Label htmlFor="game-venue" className="text-xs flex items-center gap-1.5 text-muted-foreground">
                <MapPin className="h-3.5 w-3.5" /> Venue
              </Label>
              <Input
                id="game-venue"
                type="text"
                placeholder="e.g. City Sports Centre, Court 3"
                value={venue}
                onChange={(e) => setVenue(e.target.value)}
                disabled={isLoading}
                className="text-sm"
                maxLength={100}
              />
            </div>

            {/* Duration */}
            <div className="space-y-1.5">
              <Label htmlFor="game-duration" className="text-xs flex items-center gap-1.5 text-muted-foreground">
                <Timer className="h-3.5 w-3.5" /> Duration (hours)
              </Label>
              <Input
                id="game-duration"
                type="number"
                placeholder="e.g. 2"
                value={duration}
                onChange={(e) => setDuration(e.target.value)}
                disabled={isLoading}
                className="text-sm"
                min={1}
                max={24}
                step={1}
              />
            </div>
          </div>

          {/* Submit */}
          <Button
            type="submit"
            className="w-full"
            size="lg"
            disabled={isLoading}
          >
            {isLoading ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                Creating Game…
              </>
            ) : (
              submitLabel
            )}
          </Button>
        </form>
      </CardContent>
    </Card>
  );
}
