/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    bio?: string;
    name: string;
    mobileNumber: string;
    workField?: string;
    profilePicture?: string;
}
export type Time = bigint;
export interface CourtAssignment {
    court: Court;
    players: Array<PlayerId>;
}
export interface RoundAssignments {
    assignments: Array<CourtAssignment>;
    waitlist: Array<PlayerId>;
    round: bigint;
}
export type SessionId = string;
export type GameCode = string;
export type MatchId = bigint;
export type PlayerId = Principal;
export interface SessionCreationResult {
    state: SessionState;
    sessionId: SessionId;
    config: SessionConfig;
}
export interface MatchResult {
    court: Court;
    players: Array<PlayerId>;
    timestamp: Time;
    outcome: GameOutcome;
}
export interface SessionConfig {
    isRanked: boolean;
    duration?: bigint;
    sessionCode: GameCode;
    sessionType: SessionType;
    venue?: string;
    date?: string;
    host: PlayerId;
    time?: string;
    creationTime: Time;
    sessionId: SessionId;
    courts: bigint;
}
export interface AllGamesRoundAssignments {
    round: bigint;
    roundAssignments: Array<RoundAssignments>;
}
export type Court = bigint;
export interface SessionState {
    assignments: Array<CourtAssignment>;
    isCompleted: boolean;
    previousWaitlist: Array<PlayerId>;
    currentRound: bigint;
    waitlist: Array<PlayerId>;
    matches: Array<MatchResult>;
    players: Array<PlayerId>;
    allGamesAssignments: Array<AllGamesRoundAssignments>;
    config: SessionConfig;
}
export enum GameOutcome {
    teamAWin = "teamAWin",
    teamBWin = "teamBWin"
}
export enum SessionType {
    randomAllotment = "randomAllotment",
    kingQueenOfTheCourt = "kingQueenOfTheCourt",
    roundRobin = "roundRobin",
    ladderLeague = "ladderLeague"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addPlayerToSession(sessionId: SessionId, playerName: string, mobileNumber: string, bio: string | null, profilePicture: string | null, workField: string | null): Promise<void>;
    allocatePlayers(sessionId: SessionId): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createPlayerProfile(name: string): Promise<PlayerId>;
    createSession(courts: bigint, date: string | null, time: string | null, venue: string | null, duration: bigint | null, sessionCode: GameCode, sessionType: SessionType, isRanked: boolean): Promise<SessionCreationResult>;
    endGame(sessionId: SessionId): Promise<void>;
    endRound(sessionId: SessionId): Promise<void>;
    getAllGames(sessionId: SessionId, rotations: bigint, roundsPerRotation: bigint): Promise<Array<AllGamesRoundAssignments>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getSessionGameInfo(sessionId: SessionId): Promise<[string, string | null, string | null, string | null, bigint | null]>;
    getSessionState(sessionId: SessionId): Promise<SessionState>;
    getSessionStateByCode(sessionCode: string): Promise<SessionState>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    joinSession(sessionId: SessionId): Promise<void>;
    joinSessionByCode(sessionCode: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitMatchResult(sessionId: SessionId, court: Court, outcome: GameOutcome): Promise<MatchId>;
}
import type { AllGamesRoundAssignments as _AllGamesRoundAssignments, Court as _Court, CourtAssignment as _CourtAssignment, GameCode as _GameCode, GameOutcome as _GameOutcome, MatchResult as _MatchResult, PlayerId as _PlayerId, SessionConfig as _SessionConfig, SessionCreationResult as _SessionCreationResult, SessionId as _SessionId, SessionState as _SessionState, SessionType as _SessionType, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addPlayerToSession(arg0: SessionId, arg1: string, arg2: string, arg3: string | null, arg4: string | null, arg5: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPlayerToSession(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPlayerToSession(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async allocatePlayers(arg0: SessionId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.allocatePlayers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.allocatePlayers(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n2(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n2(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createPlayerProfile(arg0: string): Promise<PlayerId> {
        if (this.processError) {
            try {
                const result = await this.actor.createPlayerProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPlayerProfile(arg0);
            return result;
        }
    }
    async createSession(arg0: bigint, arg1: string | null, arg2: string | null, arg3: string | null, arg4: bigint | null, arg5: GameCode, arg6: SessionType, arg7: boolean): Promise<SessionCreationResult> {
        if (this.processError) {
            try {
                const result = await this.actor.createSession(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg4), arg5, to_candid_SessionType_n5(this._uploadFile, this._downloadFile, arg6), arg7);
                return from_candid_SessionCreationResult_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSession(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg4), arg5, to_candid_SessionType_n5(this._uploadFile, this._downloadFile, arg6), arg7);
            return from_candid_SessionCreationResult_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async endGame(arg0: SessionId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.endGame(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.endGame(arg0);
            return result;
        }
    }
    async endRound(arg0: SessionId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.endRound(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.endRound(arg0);
            return result;
        }
    }
    async getAllGames(arg0: SessionId, arg1: bigint, arg2: bigint): Promise<Array<AllGamesRoundAssignments>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGames(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGames(arg0, arg1, arg2);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSessionGameInfo(arg0: SessionId): Promise<[string, string | null, string | null, string | null, bigint | null]> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessionGameInfo(arg0);
                return [
                    result[0],
                    from_candid_opt_n21(this._uploadFile, this._downloadFile, result[1]),
                    from_candid_opt_n21(this._uploadFile, this._downloadFile, result[2]),
                    from_candid_opt_n21(this._uploadFile, this._downloadFile, result[3]),
                    from_candid_opt_n18(this._uploadFile, this._downloadFile, result[4])
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessionGameInfo(arg0);
            return [
                result[0],
                from_candid_opt_n21(this._uploadFile, this._downloadFile, result[1]),
                from_candid_opt_n21(this._uploadFile, this._downloadFile, result[2]),
                from_candid_opt_n21(this._uploadFile, this._downloadFile, result[3]),
                from_candid_opt_n18(this._uploadFile, this._downloadFile, result[4])
            ];
        }
    }
    async getSessionState(arg0: SessionId): Promise<SessionState> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessionState(arg0);
                return from_candid_SessionState_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessionState(arg0);
            return from_candid_SessionState_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSessionStateByCode(arg0: string): Promise<SessionState> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessionStateByCode(arg0);
                return from_candid_SessionState_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessionStateByCode(arg0);
            return from_candid_SessionState_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async joinSession(arg0: SessionId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.joinSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinSession(arg0);
            return result;
        }
    }
    async joinSessionByCode(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.joinSessionByCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinSessionByCode(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n27(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n27(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitMatchResult(arg0: SessionId, arg1: Court, arg2: GameOutcome): Promise<MatchId> {
        if (this.processError) {
            try {
                const result = await this.actor.submitMatchResult(arg0, arg1, to_candid_GameOutcome_n29(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitMatchResult(arg0, arg1, to_candid_GameOutcome_n29(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
}
function from_candid_GameOutcome_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameOutcome): GameOutcome {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_MatchResult_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchResult): MatchResult {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_SessionConfig_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionConfig): SessionConfig {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_SessionCreationResult_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionCreationResult): SessionCreationResult {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_SessionState_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionState): SessionState {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_SessionType_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionType): SessionType {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    assignments: Array<_CourtAssignment>;
    isCompleted: boolean;
    previousWaitlist: Array<_PlayerId>;
    currentRound: bigint;
    waitlist: Array<_PlayerId>;
    matches: Array<_MatchResult>;
    players: Array<_PlayerId>;
    allGamesAssignments: Array<_AllGamesRoundAssignments>;
    config: _SessionConfig;
}): {
    assignments: Array<CourtAssignment>;
    isCompleted: boolean;
    previousWaitlist: Array<PlayerId>;
    currentRound: bigint;
    waitlist: Array<PlayerId>;
    matches: Array<MatchResult>;
    players: Array<PlayerId>;
    allGamesAssignments: Array<AllGamesRoundAssignments>;
    config: SessionConfig;
} {
    return {
        assignments: value.assignments,
        isCompleted: value.isCompleted,
        previousWaitlist: value.previousWaitlist,
        currentRound: value.currentRound,
        waitlist: value.waitlist,
        matches: from_candid_vec_n11(_uploadFile, _downloadFile, value.matches),
        players: value.players,
        allGamesAssignments: value.allGamesAssignments,
        config: from_candid_SessionConfig_n16(_uploadFile, _downloadFile, value.config)
    };
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    court: _Court;
    players: Array<_PlayerId>;
    timestamp: _Time;
    outcome: _GameOutcome;
}): {
    court: Court;
    players: Array<PlayerId>;
    timestamp: Time;
    outcome: GameOutcome;
} {
    return {
        court: value.court,
        players: value.players,
        timestamp: value.timestamp,
        outcome: from_candid_GameOutcome_n14(_uploadFile, _downloadFile, value.outcome)
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    isRanked: boolean;
    duration: [] | [bigint];
    sessionCode: _GameCode;
    sessionType: _SessionType;
    venue: [] | [string];
    date: [] | [string];
    host: _PlayerId;
    time: [] | [string];
    creationTime: _Time;
    sessionId: _SessionId;
    courts: bigint;
}): {
    isRanked: boolean;
    duration?: bigint;
    sessionCode: GameCode;
    sessionType: SessionType;
    venue?: string;
    date?: string;
    host: PlayerId;
    time?: string;
    creationTime: Time;
    sessionId: SessionId;
    courts: bigint;
} {
    return {
        isRanked: value.isRanked,
        duration: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.duration)),
        sessionCode: value.sessionCode,
        sessionType: from_candid_SessionType_n19(_uploadFile, _downloadFile, value.sessionType),
        venue: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.venue)),
        date: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.date)),
        host: value.host,
        time: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.time)),
        creationTime: value.creationTime,
        sessionId: value.sessionId,
        courts: value.courts
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: [] | [string];
    name: string;
    mobileNumber: string;
    workField: [] | [string];
    profilePicture: [] | [string];
}): {
    bio?: string;
    name: string;
    mobileNumber: string;
    workField?: string;
    profilePicture?: string;
} {
    return {
        bio: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.bio)),
        name: value.name,
        mobileNumber: value.mobileNumber,
        workField: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.workField)),
        profilePicture: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.profilePicture))
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    state: _SessionState;
    sessionId: _SessionId;
    config: _SessionConfig;
}): {
    state: SessionState;
    sessionId: SessionId;
    config: SessionConfig;
} {
    return {
        state: from_candid_SessionState_n9(_uploadFile, _downloadFile, value.state),
        sessionId: value.sessionId,
        config: from_candid_SessionConfig_n16(_uploadFile, _downloadFile, value.config)
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    teamAWin: null;
} | {
    teamBWin: null;
}): GameOutcome {
    return "teamAWin" in value ? GameOutcome.teamAWin : "teamBWin" in value ? GameOutcome.teamBWin : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    randomAllotment: null;
} | {
    kingQueenOfTheCourt: null;
} | {
    roundRobin: null;
} | {
    ladderLeague: null;
}): SessionType {
    return "randomAllotment" in value ? SessionType.randomAllotment : "kingQueenOfTheCourt" in value ? SessionType.kingQueenOfTheCourt : "roundRobin" in value ? SessionType.roundRobin : "ladderLeague" in value ? SessionType.ladderLeague : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MatchResult>): Array<MatchResult> {
    return value.map((x)=>from_candid_MatchResult_n12(_uploadFile, _downloadFile, x));
}
function to_candid_GameOutcome_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GameOutcome): _GameOutcome {
    return to_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function to_candid_SessionType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SessionType): _SessionType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n28(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio?: string;
    name: string;
    mobileNumber: string;
    workField?: string;
    profilePicture?: string;
}): {
    bio: [] | [string];
    name: string;
    mobileNumber: string;
    workField: [] | [string];
    profilePicture: [] | [string];
} {
    return {
        bio: value.bio ? candid_some(value.bio) : candid_none(),
        name: value.name,
        mobileNumber: value.mobileNumber,
        workField: value.workField ? candid_some(value.workField) : candid_none(),
        profilePicture: value.profilePicture ? candid_some(value.profilePicture) : candid_none()
    };
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GameOutcome): {
    teamAWin: null;
} | {
    teamBWin: null;
} {
    return value == GameOutcome.teamAWin ? {
        teamAWin: null
    } : value == GameOutcome.teamBWin ? {
        teamBWin: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SessionType): {
    randomAllotment: null;
} | {
    kingQueenOfTheCourt: null;
} | {
    roundRobin: null;
} | {
    ladderLeague: null;
} {
    return value == SessionType.randomAllotment ? {
        randomAllotment: null
    } : value == SessionType.kingQueenOfTheCourt ? {
        kingQueenOfTheCourt: null
    } : value == SessionType.roundRobin ? {
        roundRobin: null
    } : value == SessionType.ladderLeague ? {
        ladderLeague: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
