/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    bio?: string;
    name: string;
    mobileNumber: string;
    workField?: string;
    profilePicture?: string;
}
export interface MatchHistory {
    matches: Array<CompletedMatch>;
}
export type Time = bigint;
export interface CourtAssignment {
    court: Court;
    players: Array<PlayerId>;
}
export interface RoundAssignments {
    assignments: Array<CourtAssignment>;
    waitlist: Array<PlayerId>;
    round: bigint;
}
export type SessionId = string;
export interface PlayerSearchResult {
    id: Principal;
    name: string;
    mobileNumber: string;
}
export type GameCode = string;
export type PlayerId = Principal;
export interface SessionCreationResult {
    state: SessionState;
    sessionId: SessionId;
    config: SessionConfig;
}
export interface PublicProfile {
    id: Principal;
    bio?: string;
    name: string;
    workField?: string;
    profilePicture?: string;
    winRate?: number;
    winLossRecord?: [bigint, bigint];
}
export interface SessionConfig {
    isRanked: boolean;
    duration?: bigint;
    sessionCode: GameCode;
    sessionType: SessionType;
    venue?: string;
    date?: string;
    host: PlayerId;
    time?: string;
    creationTime: Time;
    sessionId: SessionId;
    courts: bigint;
}
export interface MatchResult {
    court: Court;
    players: Array<PlayerId>;
    timestamp: Time;
    outcome: GameOutcome;
}
export interface CompletedMatch {
    teamScores: [bigint, bigint];
    date: Time;
    court: Court;
    opponentNames: Array<string>;
    sessionId: SessionId;
    outcome: GameOutcome;
}
export interface GuestPlayer {
    isGuest: boolean;
    name: string;
    guestId: GuestId;
}
export interface Message {
    text: string;
    recipient: Principal;
    sender: Principal;
    timestamp: Time;
}
export interface SessionNotFound {
    message: string;
    reason?: string;
}
export type GuestId = bigint;
export type Court = bigint;
export interface AllGamesRoundAssignments {
    round: bigint;
    roundAssignments: Array<RoundAssignments>;
}
export interface Conversation {
    messages: Array<Message>;
    participant: Principal;
}
export interface SessionState {
    assignments: Array<CourtAssignment>;
    isCompleted: boolean;
    previousWaitlist: Array<PlayerId>;
    currentRound: bigint;
    guestPlayers: Array<GuestPlayer>;
    waitlist: Array<PlayerId>;
    matches: Array<MatchResult>;
    players: Array<PlayerId>;
    allGamesAssignments: Array<AllGamesRoundAssignments>;
    lastGuestId: GuestId;
    config: SessionConfig;
}
export enum GameOutcome {
    teamAWin = "teamAWin",
    teamBWin = "teamBWin"
}
export enum SessionType {
    randomAllotment = "randomAllotment",
    kingQueenOfTheCourt = "kingQueenOfTheCourt",
    roundRobin = "roundRobin",
    ladderLeague = "ladderLeague"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addGuestPlayer(sessionId: string, name: string): Promise<{
        __kind__: "ok";
        ok: GuestPlayer;
    } | {
        __kind__: "err";
        err: string;
    }>;
    addPlayerToSession(sessionId: SessionId, playerId: Principal): Promise<{
        __kind__: "ok";
        ok: SessionState;
    } | {
        __kind__: "err";
        err: string;
    }>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createGuestProfile(name: string, mobileNumber: string, bio: string | null, profilePicture: string | null, workField: string | null): Promise<PublicProfile>;
    createSession(courts: bigint, date: string | null, time: string | null, venue: string | null, duration: bigint | null, sessionCode: GameCode, sessionType: SessionType, isRanked: boolean): Promise<SessionCreationResult>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getConversation(otherPrincipal: Principal): Promise<Array<Message>>;
    getMailbox(): Promise<Array<Conversation>>;
    getMatchHistory(): Promise<MatchHistory>;
    getMatchHistoryForPlayer(_requested: Principal): Promise<MatchHistory>;
    getPublicProfile(requested: Principal): Promise<PublicProfile | null>;
    getSession(sessionId: SessionId): Promise<{
        __kind__: "ok";
        ok: SessionState;
    } | {
        __kind__: "err";
        err: SessionNotFound;
    }>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserProfileAdmin(_user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    joinSession(gameCode: GameCode, guestName: string): Promise<{
        __kind__: "ok";
        ok: SessionId;
    } | {
        __kind__: "err";
        err: string;
    }>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchPlayersByName(searchTerm: string): Promise<Array<PlayerSearchResult>>;
    sendMessage(recipient: Principal, text: string): Promise<void>;
}
import type { AllGamesRoundAssignments as _AllGamesRoundAssignments, CompletedMatch as _CompletedMatch, Court as _Court, CourtAssignment as _CourtAssignment, GameCode as _GameCode, GameOutcome as _GameOutcome, GuestId as _GuestId, GuestPlayer as _GuestPlayer, MatchHistory as _MatchHistory, MatchResult as _MatchResult, PlayerId as _PlayerId, PublicProfile as _PublicProfile, SessionConfig as _SessionConfig, SessionCreationResult as _SessionCreationResult, SessionId as _SessionId, SessionNotFound as _SessionNotFound, SessionState as _SessionState, SessionType as _SessionType, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addGuestPlayer(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: GuestPlayer;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addGuestPlayer(arg0, arg1);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGuestPlayer(arg0, arg1);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addPlayerToSession(arg0: SessionId, arg1: Principal): Promise<{
        __kind__: "ok";
        ok: SessionState;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addPlayerToSession(arg0, arg1);
                return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPlayerToSession(arg0, arg1);
            return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n16(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n16(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createGuestProfile(arg0: string, arg1: string, arg2: string | null, arg3: string | null, arg4: string | null): Promise<PublicProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.createGuestProfile(arg0, arg1, to_candid_opt_n18(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n18(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n18(this._uploadFile, this._downloadFile, arg4));
                return from_candid_PublicProfile_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGuestProfile(arg0, arg1, to_candid_opt_n18(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n18(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n18(this._uploadFile, this._downloadFile, arg4));
            return from_candid_PublicProfile_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async createSession(arg0: bigint, arg1: string | null, arg2: string | null, arg3: string | null, arg4: bigint | null, arg5: GameCode, arg6: SessionType, arg7: boolean): Promise<SessionCreationResult> {
        if (this.processError) {
            try {
                const result = await this.actor.createSession(arg0, to_candid_opt_n18(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n18(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n18(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg4), arg5, to_candid_SessionType_n24(this._uploadFile, this._downloadFile, arg6), arg7);
                return from_candid_SessionCreationResult_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSession(arg0, to_candid_opt_n18(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n18(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n18(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg4), arg5, to_candid_SessionType_n24(this._uploadFile, this._downloadFile, arg6), arg7);
            return from_candid_SessionCreationResult_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConversation(arg0: Principal): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversation(arg0);
            return result;
        }
    }
    async getMailbox(): Promise<Array<Conversation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMailbox();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMailbox();
            return result;
        }
    }
    async getMatchHistory(): Promise<MatchHistory> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatchHistory();
                return from_candid_MatchHistory_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatchHistory();
            return from_candid_MatchHistory_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMatchHistoryForPlayer(arg0: Principal): Promise<MatchHistory> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatchHistoryForPlayer(arg0);
                return from_candid_MatchHistory_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatchHistoryForPlayer(arg0);
            return from_candid_MatchHistory_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublicProfile(arg0: Principal): Promise<PublicProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicProfile(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicProfile(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSession(arg0: SessionId): Promise<{
        __kind__: "ok";
        ok: SessionState;
    } | {
        __kind__: "err";
        err: SessionNotFound;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getSession(arg0);
                return from_candid_variant_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSession(arg0);
            return from_candid_variant_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfileAdmin(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfileAdmin(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfileAdmin(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async joinSession(arg0: GameCode, arg1: string): Promise<{
        __kind__: "ok";
        ok: SessionId;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.joinSession(arg0, arg1);
                return from_candid_variant_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinSession(arg0, arg1);
            return from_candid_variant_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n43(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n43(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchPlayersByName(arg0: string): Promise<Array<PlayerSearchResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchPlayersByName(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchPlayersByName(arg0);
            return result;
        }
    }
    async sendMessage(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return result;
        }
    }
}
function from_candid_CompletedMatch_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CompletedMatch): CompletedMatch {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_GameOutcome_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameOutcome): GameOutcome {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_MatchHistory_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchHistory): MatchHistory {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_MatchResult_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchResult): MatchResult {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_PublicProfile_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PublicProfile): PublicProfile {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_SessionConfig_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionConfig): SessionConfig {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_SessionCreationResult_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionCreationResult): SessionCreationResult {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_SessionNotFound_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionNotFound): SessionNotFound {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_SessionState_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionState): SessionState {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_SessionType_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionType): SessionType {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [[bigint, bigint]]): [bigint, bigint] | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PublicProfile]): PublicProfile | null {
    return value.length === 0 ? null : from_candid_PublicProfile_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    isRanked: boolean;
    duration: [] | [bigint];
    sessionCode: _GameCode;
    sessionType: _SessionType;
    venue: [] | [string];
    date: [] | [string];
    host: _PlayerId;
    time: [] | [string];
    creationTime: _Time;
    sessionId: _SessionId;
    courts: bigint;
}): {
    isRanked: boolean;
    duration?: bigint;
    sessionCode: GameCode;
    sessionType: SessionType;
    venue?: string;
    date?: string;
    host: PlayerId;
    time?: string;
    creationTime: Time;
    sessionId: SessionId;
    courts: bigint;
} {
    return {
        isRanked: value.isRanked,
        duration: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.duration)),
        sessionCode: value.sessionCode,
        sessionType: from_candid_SessionType_n13(_uploadFile, _downloadFile, value.sessionType),
        venue: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.venue)),
        date: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.date)),
        host: value.host,
        time: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.time)),
        creationTime: value.creationTime,
        sessionId: value.sessionId,
        courts: value.courts
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    bio: [] | [string];
    name: string;
    workField: [] | [string];
    profilePicture: [] | [string];
    winRate: [] | [number];
    winLossRecord: [] | [[bigint, bigint]];
}): {
    id: Principal;
    bio?: string;
    name: string;
    workField?: string;
    profilePicture?: string;
    winRate?: number;
    winLossRecord?: [bigint, bigint];
} {
    return {
        id: value.id,
        bio: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.bio)),
        name: value.name,
        workField: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.workField)),
        profilePicture: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.profilePicture)),
        winRate: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.winRate)),
        winLossRecord: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.winLossRecord))
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    state: _SessionState;
    sessionId: _SessionId;
    config: _SessionConfig;
}): {
    state: SessionState;
    sessionId: SessionId;
    config: SessionConfig;
} {
    return {
        state: from_candid_SessionState_n3(_uploadFile, _downloadFile, value.state),
        sessionId: value.sessionId,
        config: from_candid_SessionConfig_n10(_uploadFile, _downloadFile, value.config)
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: [] | [string];
    name: string;
    mobileNumber: string;
    workField: [] | [string];
    profilePicture: [] | [string];
}): {
    bio?: string;
    name: string;
    mobileNumber: string;
    workField?: string;
    profilePicture?: string;
} {
    return {
        bio: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.bio)),
        name: value.name,
        mobileNumber: value.mobileNumber,
        workField: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.workField)),
        profilePicture: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.profilePicture))
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    matches: Array<_CompletedMatch>;
}): {
    matches: Array<CompletedMatch>;
} {
    return {
        matches: from_candid_vec_n35(_uploadFile, _downloadFile, value.matches)
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    teamScores: [bigint, bigint];
    date: _Time;
    court: _Court;
    opponentNames: Array<string>;
    sessionId: _SessionId;
    outcome: _GameOutcome;
}): {
    teamScores: [bigint, bigint];
    date: Time;
    court: Court;
    opponentNames: Array<string>;
    sessionId: SessionId;
    outcome: GameOutcome;
} {
    return {
        teamScores: value.teamScores,
        date: value.date,
        court: value.court,
        opponentNames: value.opponentNames,
        sessionId: value.sessionId,
        outcome: from_candid_GameOutcome_n8(_uploadFile, _downloadFile, value.outcome)
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    assignments: Array<_CourtAssignment>;
    isCompleted: boolean;
    previousWaitlist: Array<_PlayerId>;
    currentRound: bigint;
    guestPlayers: Array<_GuestPlayer>;
    waitlist: Array<_PlayerId>;
    matches: Array<_MatchResult>;
    players: Array<_PlayerId>;
    allGamesAssignments: Array<_AllGamesRoundAssignments>;
    lastGuestId: _GuestId;
    config: _SessionConfig;
}): {
    assignments: Array<CourtAssignment>;
    isCompleted: boolean;
    previousWaitlist: Array<PlayerId>;
    currentRound: bigint;
    guestPlayers: Array<GuestPlayer>;
    waitlist: Array<PlayerId>;
    matches: Array<MatchResult>;
    players: Array<PlayerId>;
    allGamesAssignments: Array<AllGamesRoundAssignments>;
    lastGuestId: GuestId;
    config: SessionConfig;
} {
    return {
        assignments: value.assignments,
        isCompleted: value.isCompleted,
        previousWaitlist: value.previousWaitlist,
        currentRound: value.currentRound,
        guestPlayers: value.guestPlayers,
        waitlist: value.waitlist,
        matches: from_candid_vec_n5(_uploadFile, _downloadFile, value.matches),
        players: value.players,
        allGamesAssignments: value.allGamesAssignments,
        lastGuestId: value.lastGuestId,
        config: from_candid_SessionConfig_n10(_uploadFile, _downloadFile, value.config)
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    message: string;
    reason: [] | [string];
}): {
    message: string;
    reason?: string;
} {
    return {
        message: value.message,
        reason: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.reason))
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    court: _Court;
    players: Array<_PlayerId>;
    timestamp: _Time;
    outcome: _GameOutcome;
}): {
    court: Court;
    players: Array<PlayerId>;
    timestamp: Time;
    outcome: GameOutcome;
} {
    return {
        court: value.court,
        players: value.players,
        timestamp: value.timestamp,
        outcome: from_candid_GameOutcome_n8(_uploadFile, _downloadFile, value.outcome)
    };
}
function from_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _GuestPlayer;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: GuestPlayer;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    randomAllotment: null;
} | {
    kingQueenOfTheCourt: null;
} | {
    roundRobin: null;
} | {
    ladderLeague: null;
}): SessionType {
    return "randomAllotment" in value ? SessionType.randomAllotment : "kingQueenOfTheCourt" in value ? SessionType.kingQueenOfTheCourt : "roundRobin" in value ? SessionType.roundRobin : "ladderLeague" in value ? SessionType.ladderLeague : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _SessionState;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: SessionState;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_SessionState_n3(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _SessionState;
} | {
    err: _SessionNotFound;
}): {
    __kind__: "ok";
    ok: SessionState;
} | {
    __kind__: "err";
    err: SessionNotFound;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_SessionState_n3(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_SessionNotFound_n40(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _SessionId;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: SessionId;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    teamAWin: null;
} | {
    teamBWin: null;
}): GameOutcome {
    return "teamAWin" in value ? GameOutcome.teamAWin : "teamBWin" in value ? GameOutcome.teamBWin : value;
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CompletedMatch>): Array<CompletedMatch> {
    return value.map((x)=>from_candid_CompletedMatch_n36(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MatchResult>): Array<MatchResult> {
    return value.map((x)=>from_candid_MatchResult_n6(_uploadFile, _downloadFile, x));
}
function to_candid_SessionType_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SessionType): _SessionType {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n44(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio?: string;
    name: string;
    mobileNumber: string;
    workField?: string;
    profilePicture?: string;
}): {
    bio: [] | [string];
    name: string;
    mobileNumber: string;
    workField: [] | [string];
    profilePicture: [] | [string];
} {
    return {
        bio: value.bio ? candid_some(value.bio) : candid_none(),
        name: value.name,
        mobileNumber: value.mobileNumber,
        workField: value.workField ? candid_some(value.workField) : candid_none(),
        profilePicture: value.profilePicture ? candid_some(value.profilePicture) : candid_none()
    };
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SessionType): {
    randomAllotment: null;
} | {
    kingQueenOfTheCourt: null;
} | {
    roundRobin: null;
} | {
    ladderLeague: null;
} {
    return value == SessionType.randomAllotment ? {
        randomAllotment: null
    } : value == SessionType.kingQueenOfTheCourt ? {
        kingQueenOfTheCourt: null
    } : value == SessionType.roundRobin ? {
        roundRobin: null
    } : value == SessionType.ladderLeague ? {
        ladderLeague: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
