/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AddPlayerResult = { 'ok' : null } |
  { 'guestAdded' : GuestPlayer } |
  { 'notHost' : null } |
  { 'invalidInput' : null } |
  { 'unknownError' : null } |
  { 'invalidGuestName' : null } |
  { 'playerAlreadyExists' : null } |
  { 'sessionNotFound' : null };
export interface AllGamesRoundAssignments {
  'round' : bigint,
  'roundAssignments' : Array<RoundAssignments>,
}
export interface CompletedMatch {
  'teamScores' : [bigint, bigint],
  'date' : Time,
  'court' : Court,
  'opponentNames' : Array<string>,
  'sessionId' : SessionId,
  'outcome' : GameOutcome,
}
export interface Conversation {
  'messages' : Array<Message>,
  'participant' : Principal,
}
export type Court = bigint;
export interface CourtAssignment {
  'court' : Court,
  'players' : Array<PlayerId>,
}
export type EndSessionResult = { 'ok' : null } |
  { 'notHost' : null } |
  { 'alreadyEnded' : null } |
  { 'sessionNotFound' : null };
export type GameCode = string;
export type GameOutcome = { 'teamAWin' : null } |
  { 'teamBWin' : null };
export type GuestId = bigint;
export interface GuestPlayer {
  'isGuest' : boolean,
  'name' : string,
  'guestId' : GuestId,
}
export interface MatchHistory { 'matches' : Array<CompletedMatch> }
export interface MatchResult {
  'court' : Court,
  'players' : Array<PlayerId>,
  'timestamp' : Time,
  'outcome' : GameOutcome,
}
export interface Message {
  'text' : string,
  'recipient' : Principal,
  'sender' : Principal,
  'timestamp' : Time,
}
export type PlayerId = Principal;
export interface PlayerSearchResult {
  'id' : Principal,
  'name' : string,
  'mobileNumber' : string,
}
export interface PublicProfile {
  'id' : Principal,
  'bio' : [] | [string],
  'name' : string,
  'workField' : [] | [string],
  'profilePicture' : [] | [string],
  'winRate' : [] | [number],
  'winLossRecord' : [] | [[bigint, bigint]],
}
export interface RoundAssignments {
  'assignments' : Array<CourtAssignment>,
  'waitlist' : Array<PlayerId>,
  'round' : bigint,
}
export interface SessionConfig {
  'isRanked' : boolean,
  'duration' : [] | [bigint],
  'sessionCode' : GameCode,
  'sessionType' : SessionType,
  'venue' : [] | [string],
  'date' : [] | [string],
  'host' : PlayerId,
  'time' : [] | [string],
  'creationTime' : Time,
  'sessionId' : SessionId,
  'courts' : bigint,
}
export interface SessionCreationResult {
  'state' : SessionState,
  'sessionId' : SessionId,
  'config' : SessionConfig,
}
export type SessionId = string;
export interface SessionNotFound {
  'message' : string,
  'reason' : [] | [string],
}
export interface SessionState {
  'assignments' : Array<CourtAssignment>,
  'isCompleted' : boolean,
  'previousWaitlist' : Array<PlayerId>,
  'currentRound' : bigint,
  'guestPlayers' : Array<GuestPlayer>,
  'waitlist' : Array<PlayerId>,
  'matches' : Array<MatchResult>,
  'players' : Array<PlayerId>,
  'allGamesAssignments' : Array<AllGamesRoundAssignments>,
  'lastGuestId' : GuestId,
  'config' : SessionConfig,
}
export type SessionType = { 'randomAllotment' : null } |
  { 'kingQueenOfTheCourt' : null } |
  { 'roundRobin' : null } |
  { 'ladderLeague' : null };
export type Time = bigint;
export interface UserProfile {
  'bio' : [] | [string],
  'name' : string,
  'mobileNumber' : string,
  'workField' : [] | [string],
  'profilePicture' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createGuestProfile' : ActorMethod<
    [string, string, [] | [string], [] | [string], [] | [string]],
    PublicProfile
  >,
  'createSession' : ActorMethod<
    [
      bigint,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [bigint],
      GameCode,
      SessionType,
      boolean,
    ],
    SessionCreationResult
  >,
  'endSession' : ActorMethod<[SessionId], EndSessionResult>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConversation' : ActorMethod<[Principal], Array<Message>>,
  'getMailbox' : ActorMethod<[], Array<Conversation>>,
  'getMatchHistory' : ActorMethod<[], MatchHistory>,
  'getMatchHistoryForPlayer' : ActorMethod<[Principal], MatchHistory>,
  'getPublicProfile' : ActorMethod<[Principal], [] | [PublicProfile]>,
  'getSession' : ActorMethod<
    [SessionId],
    { 'ok' : SessionState } |
      { 'err' : SessionNotFound }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProfileAdmin' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hostAddPlayer' : ActorMethod<
    [SessionId, [] | [Principal], [] | [string]],
    AddPlayerResult
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinSession' : ActorMethod<
    [GameCode, string],
    { 'ok' : SessionId } |
      { 'err' : string }
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchPlayers' : ActorMethod<[string], Array<PlayerSearchResult>>,
  'sendMessage' : ActorMethod<[Principal, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];