/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SessionId = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PlayerId = IDL.Principal;
export const Court = IDL.Nat;
export const CourtAssignment = IDL.Record({
  'court' : Court,
  'players' : IDL.Vec(PlayerId),
});
export const Time = IDL.Int;
export const GameOutcome = IDL.Variant({
  'teamAWin' : IDL.Null,
  'teamBWin' : IDL.Null,
});
export const MatchResult = IDL.Record({
  'court' : Court,
  'players' : IDL.Vec(PlayerId),
  'timestamp' : Time,
  'outcome' : GameOutcome,
});
export const RoundAssignments = IDL.Record({
  'assignments' : IDL.Vec(CourtAssignment),
  'waitlist' : IDL.Vec(PlayerId),
  'round' : IDL.Nat,
});
export const SessionConfig = IDL.Record({
  'host' : PlayerId,
  'creationTime' : Time,
  'sessionId' : SessionId,
  'courts' : IDL.Nat,
});
export const SessionState = IDL.Record({
  'assignments' : IDL.Vec(CourtAssignment),
  'currentRound' : IDL.Nat,
  'waitlist' : IDL.Vec(PlayerId),
  'matches' : IDL.Vec(MatchResult),
  'players' : IDL.Vec(PlayerId),
  'allRounds' : IDL.Vec(RoundAssignments),
  'config' : SessionConfig,
});
export const SessionCreationResult = IDL.Record({
  'state' : SessionState,
  'sessionId' : SessionId,
  'config' : SessionConfig,
});
export const UserProfile = IDL.Record({
  'duprRating' : IDL.Opt(IDL.Float64),
  'name' : IDL.Text,
});
export const MatchId = IDL.Nat;

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPlayerToSession' : IDL.Func(
      [SessionId, IDL.Text, IDL.Opt(IDL.Float64)],
      [],
      [],
    ),
  'allocatePlayers' : IDL.Func([SessionId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPlayerProfile' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Float64)],
      [PlayerId],
      [],
    ),
  'createSession' : IDL.Func([IDL.Nat], [SessionCreationResult], []),
  'getAllMatchups' : IDL.Func(
      [SessionId, IDL.Nat],
      [IDL.Vec(RoundAssignments)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getSessionState' : IDL.Func([SessionId], [SessionState], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinSession' : IDL.Func([SessionId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitMatchResult' : IDL.Func(
      [SessionId, Court, GameOutcome],
      [MatchId],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SessionId = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PlayerId = IDL.Principal;
  const Court = IDL.Nat;
  const CourtAssignment = IDL.Record({
    'court' : Court,
    'players' : IDL.Vec(PlayerId),
  });
  const Time = IDL.Int;
  const GameOutcome = IDL.Variant({
    'teamAWin' : IDL.Null,
    'teamBWin' : IDL.Null,
  });
  const MatchResult = IDL.Record({
    'court' : Court,
    'players' : IDL.Vec(PlayerId),
    'timestamp' : Time,
    'outcome' : GameOutcome,
  });
  const RoundAssignments = IDL.Record({
    'assignments' : IDL.Vec(CourtAssignment),
    'waitlist' : IDL.Vec(PlayerId),
    'round' : IDL.Nat,
  });
  const SessionConfig = IDL.Record({
    'host' : PlayerId,
    'creationTime' : Time,
    'sessionId' : SessionId,
    'courts' : IDL.Nat,
  });
  const SessionState = IDL.Record({
    'assignments' : IDL.Vec(CourtAssignment),
    'currentRound' : IDL.Nat,
    'waitlist' : IDL.Vec(PlayerId),
    'matches' : IDL.Vec(MatchResult),
    'players' : IDL.Vec(PlayerId),
    'allRounds' : IDL.Vec(RoundAssignments),
    'config' : SessionConfig,
  });
  const SessionCreationResult = IDL.Record({
    'state' : SessionState,
    'sessionId' : SessionId,
    'config' : SessionConfig,
  });
  const UserProfile = IDL.Record({
    'duprRating' : IDL.Opt(IDL.Float64),
    'name' : IDL.Text,
  });
  const MatchId = IDL.Nat;
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPlayerToSession' : IDL.Func(
        [SessionId, IDL.Text, IDL.Opt(IDL.Float64)],
        [],
        [],
      ),
    'allocatePlayers' : IDL.Func([SessionId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPlayerProfile' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Float64)],
        [PlayerId],
        [],
      ),
    'createSession' : IDL.Func([IDL.Nat], [SessionCreationResult], []),
    'getAllMatchups' : IDL.Func(
        [SessionId, IDL.Nat],
        [IDL.Vec(RoundAssignments)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getSessionState' : IDL.Func([SessionId], [SessionState], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinSession' : IDL.Func([SessionId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitMatchResult' : IDL.Func(
        [SessionId, Court, GameOutcome],
        [MatchId],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };