/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PublicProfile = IDL.Record({
  'id' : IDL.Principal,
  'bio' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'workField' : IDL.Opt(IDL.Text),
  'profilePicture' : IDL.Opt(IDL.Text),
  'winRate' : IDL.Opt(IDL.Float64),
  'winLossRecord' : IDL.Opt(IDL.Tuple(IDL.Nat, IDL.Nat)),
});
export const GameCode = IDL.Text;
export const SessionType = IDL.Variant({
  'randomAllotment' : IDL.Null,
  'kingQueenOfTheCourt' : IDL.Null,
  'roundRobin' : IDL.Null,
  'ladderLeague' : IDL.Null,
});
export const Court = IDL.Nat;
export const PlayerId = IDL.Principal;
export const CourtAssignment = IDL.Record({
  'court' : Court,
  'players' : IDL.Vec(PlayerId),
});
export const GuestId = IDL.Nat;
export const GuestPlayer = IDL.Record({
  'isGuest' : IDL.Bool,
  'name' : IDL.Text,
  'guestId' : GuestId,
});
export const Time = IDL.Int;
export const GameOutcome = IDL.Variant({
  'teamAWin' : IDL.Null,
  'teamBWin' : IDL.Null,
});
export const MatchResult = IDL.Record({
  'court' : Court,
  'players' : IDL.Vec(PlayerId),
  'timestamp' : Time,
  'outcome' : GameOutcome,
});
export const RoundAssignments = IDL.Record({
  'assignments' : IDL.Vec(CourtAssignment),
  'waitlist' : IDL.Vec(PlayerId),
  'round' : IDL.Nat,
});
export const AllGamesRoundAssignments = IDL.Record({
  'round' : IDL.Nat,
  'roundAssignments' : IDL.Vec(RoundAssignments),
});
export const SessionId = IDL.Text;
export const SessionConfig = IDL.Record({
  'isRanked' : IDL.Bool,
  'duration' : IDL.Opt(IDL.Nat),
  'sessionCode' : GameCode,
  'sessionType' : SessionType,
  'venue' : IDL.Opt(IDL.Text),
  'date' : IDL.Opt(IDL.Text),
  'host' : PlayerId,
  'time' : IDL.Opt(IDL.Text),
  'creationTime' : Time,
  'sessionId' : SessionId,
  'courts' : IDL.Nat,
});
export const SessionState = IDL.Record({
  'assignments' : IDL.Vec(CourtAssignment),
  'isCompleted' : IDL.Bool,
  'previousWaitlist' : IDL.Vec(PlayerId),
  'currentRound' : IDL.Nat,
  'guestPlayers' : IDL.Vec(GuestPlayer),
  'waitlist' : IDL.Vec(PlayerId),
  'matches' : IDL.Vec(MatchResult),
  'players' : IDL.Vec(PlayerId),
  'allGamesAssignments' : IDL.Vec(AllGamesRoundAssignments),
  'lastGuestId' : GuestId,
  'config' : SessionConfig,
});
export const SessionCreationResult = IDL.Record({
  'state' : SessionState,
  'sessionId' : SessionId,
  'config' : SessionConfig,
});
export const EndSessionResult = IDL.Variant({
  'ok' : IDL.Null,
  'notHost' : IDL.Null,
  'alreadyEnded' : IDL.Null,
  'sessionNotFound' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'workField' : IDL.Opt(IDL.Text),
  'profilePicture' : IDL.Opt(IDL.Text),
});
export const Message = IDL.Record({
  'text' : IDL.Text,
  'recipient' : IDL.Principal,
  'sender' : IDL.Principal,
  'timestamp' : Time,
});
export const Conversation = IDL.Record({
  'messages' : IDL.Vec(Message),
  'participant' : IDL.Principal,
});
export const CompletedMatch = IDL.Record({
  'teamScores' : IDL.Tuple(IDL.Nat, IDL.Nat),
  'date' : Time,
  'court' : Court,
  'opponentNames' : IDL.Vec(IDL.Text),
  'sessionId' : SessionId,
  'outcome' : GameOutcome,
});
export const MatchHistory = IDL.Record({ 'matches' : IDL.Vec(CompletedMatch) });
export const SessionNotFound = IDL.Record({
  'message' : IDL.Text,
  'reason' : IDL.Opt(IDL.Text),
});
export const AddPlayerResult = IDL.Variant({
  'ok' : IDL.Null,
  'guestAdded' : GuestPlayer,
  'notHost' : IDL.Null,
  'invalidInput' : IDL.Null,
  'unknownError' : IDL.Null,
  'invalidGuestName' : IDL.Null,
  'playerAlreadyExists' : IDL.Null,
  'sessionNotFound' : IDL.Null,
});
export const PlayerSearchResult = IDL.Record({
  'id' : IDL.Principal,
  'name' : IDL.Text,
  'mobileNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createGuestProfile' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [PublicProfile],
      [],
    ),
  'createSession' : IDL.Func(
      [
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
        GameCode,
        SessionType,
        IDL.Bool,
      ],
      [SessionCreationResult],
      [],
    ),
  'endSession' : IDL.Func([SessionId], [EndSessionResult], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversation' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
  'getMailbox' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
  'getMatchHistory' : IDL.Func([], [MatchHistory], ['query']),
  'getMatchHistoryForPlayer' : IDL.Func(
      [IDL.Principal],
      [MatchHistory],
      ['query'],
    ),
  'getPublicProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PublicProfile)],
      ['query'],
    ),
  'getSession' : IDL.Func(
      [SessionId],
      [IDL.Variant({ 'ok' : SessionState, 'err' : SessionNotFound })],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProfileAdmin' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hostAddPlayer' : IDL.Func(
      [SessionId, IDL.Opt(IDL.Principal), IDL.Opt(IDL.Text)],
      [AddPlayerResult],
      [],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinSession' : IDL.Func(
      [GameCode, IDL.Text],
      [IDL.Variant({ 'ok' : SessionId, 'err' : IDL.Text })],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchPlayers' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PlayerSearchResult)],
      ['query'],
    ),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PublicProfile = IDL.Record({
    'id' : IDL.Principal,
    'bio' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'workField' : IDL.Opt(IDL.Text),
    'profilePicture' : IDL.Opt(IDL.Text),
    'winRate' : IDL.Opt(IDL.Float64),
    'winLossRecord' : IDL.Opt(IDL.Tuple(IDL.Nat, IDL.Nat)),
  });
  const GameCode = IDL.Text;
  const SessionType = IDL.Variant({
    'randomAllotment' : IDL.Null,
    'kingQueenOfTheCourt' : IDL.Null,
    'roundRobin' : IDL.Null,
    'ladderLeague' : IDL.Null,
  });
  const Court = IDL.Nat;
  const PlayerId = IDL.Principal;
  const CourtAssignment = IDL.Record({
    'court' : Court,
    'players' : IDL.Vec(PlayerId),
  });
  const GuestId = IDL.Nat;
  const GuestPlayer = IDL.Record({
    'isGuest' : IDL.Bool,
    'name' : IDL.Text,
    'guestId' : GuestId,
  });
  const Time = IDL.Int;
  const GameOutcome = IDL.Variant({
    'teamAWin' : IDL.Null,
    'teamBWin' : IDL.Null,
  });
  const MatchResult = IDL.Record({
    'court' : Court,
    'players' : IDL.Vec(PlayerId),
    'timestamp' : Time,
    'outcome' : GameOutcome,
  });
  const RoundAssignments = IDL.Record({
    'assignments' : IDL.Vec(CourtAssignment),
    'waitlist' : IDL.Vec(PlayerId),
    'round' : IDL.Nat,
  });
  const AllGamesRoundAssignments = IDL.Record({
    'round' : IDL.Nat,
    'roundAssignments' : IDL.Vec(RoundAssignments),
  });
  const SessionId = IDL.Text;
  const SessionConfig = IDL.Record({
    'isRanked' : IDL.Bool,
    'duration' : IDL.Opt(IDL.Nat),
    'sessionCode' : GameCode,
    'sessionType' : SessionType,
    'venue' : IDL.Opt(IDL.Text),
    'date' : IDL.Opt(IDL.Text),
    'host' : PlayerId,
    'time' : IDL.Opt(IDL.Text),
    'creationTime' : Time,
    'sessionId' : SessionId,
    'courts' : IDL.Nat,
  });
  const SessionState = IDL.Record({
    'assignments' : IDL.Vec(CourtAssignment),
    'isCompleted' : IDL.Bool,
    'previousWaitlist' : IDL.Vec(PlayerId),
    'currentRound' : IDL.Nat,
    'guestPlayers' : IDL.Vec(GuestPlayer),
    'waitlist' : IDL.Vec(PlayerId),
    'matches' : IDL.Vec(MatchResult),
    'players' : IDL.Vec(PlayerId),
    'allGamesAssignments' : IDL.Vec(AllGamesRoundAssignments),
    'lastGuestId' : GuestId,
    'config' : SessionConfig,
  });
  const SessionCreationResult = IDL.Record({
    'state' : SessionState,
    'sessionId' : SessionId,
    'config' : SessionConfig,
  });
  const EndSessionResult = IDL.Variant({
    'ok' : IDL.Null,
    'notHost' : IDL.Null,
    'alreadyEnded' : IDL.Null,
    'sessionNotFound' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'workField' : IDL.Opt(IDL.Text),
    'profilePicture' : IDL.Opt(IDL.Text),
  });
  const Message = IDL.Record({
    'text' : IDL.Text,
    'recipient' : IDL.Principal,
    'sender' : IDL.Principal,
    'timestamp' : Time,
  });
  const Conversation = IDL.Record({
    'messages' : IDL.Vec(Message),
    'participant' : IDL.Principal,
  });
  const CompletedMatch = IDL.Record({
    'teamScores' : IDL.Tuple(IDL.Nat, IDL.Nat),
    'date' : Time,
    'court' : Court,
    'opponentNames' : IDL.Vec(IDL.Text),
    'sessionId' : SessionId,
    'outcome' : GameOutcome,
  });
  const MatchHistory = IDL.Record({ 'matches' : IDL.Vec(CompletedMatch) });
  const SessionNotFound = IDL.Record({
    'message' : IDL.Text,
    'reason' : IDL.Opt(IDL.Text),
  });
  const AddPlayerResult = IDL.Variant({
    'ok' : IDL.Null,
    'guestAdded' : GuestPlayer,
    'notHost' : IDL.Null,
    'invalidInput' : IDL.Null,
    'unknownError' : IDL.Null,
    'invalidGuestName' : IDL.Null,
    'playerAlreadyExists' : IDL.Null,
    'sessionNotFound' : IDL.Null,
  });
  const PlayerSearchResult = IDL.Record({
    'id' : IDL.Principal,
    'name' : IDL.Text,
    'mobileNumber' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createGuestProfile' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [PublicProfile],
        [],
      ),
    'createSession' : IDL.Func(
        [
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          GameCode,
          SessionType,
          IDL.Bool,
        ],
        [SessionCreationResult],
        [],
      ),
    'endSession' : IDL.Func([SessionId], [EndSessionResult], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversation' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getMailbox' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
    'getMatchHistory' : IDL.Func([], [MatchHistory], ['query']),
    'getMatchHistoryForPlayer' : IDL.Func(
        [IDL.Principal],
        [MatchHistory],
        ['query'],
      ),
    'getPublicProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PublicProfile)],
        ['query'],
      ),
    'getSession' : IDL.Func(
        [SessionId],
        [IDL.Variant({ 'ok' : SessionState, 'err' : SessionNotFound })],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProfileAdmin' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hostAddPlayer' : IDL.Func(
        [SessionId, IDL.Opt(IDL.Principal), IDL.Opt(IDL.Text)],
        [AddPlayerResult],
        [],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinSession' : IDL.Func(
        [GameCode, IDL.Text],
        [IDL.Variant({ 'ok' : SessionId, 'err' : IDL.Text })],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchPlayers' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PlayerSearchResult)],
        ['query'],
      ),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };