/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AllGamesRoundAssignments {
  'round' : bigint,
  'roundAssignments' : Array<RoundAssignments>,
}
export type Court = bigint;
export interface CourtAssignment {
  'court' : Court,
  'players' : Array<PlayerId>,
}
export type GameCode = string;
export type GameOutcome = { 'teamAWin' : null } |
  { 'teamBWin' : null };
export type MatchId = bigint;
export interface MatchResult {
  'court' : Court,
  'players' : Array<PlayerId>,
  'timestamp' : Time,
  'outcome' : GameOutcome,
}
export type PlayerId = Principal;
export interface RoundAssignments {
  'assignments' : Array<CourtAssignment>,
  'waitlist' : Array<PlayerId>,
  'round' : bigint,
}
export interface SessionConfig {
  'isRanked' : boolean,
  'duration' : [] | [bigint],
  'sessionCode' : GameCode,
  'sessionType' : SessionType,
  'venue' : [] | [string],
  'date' : [] | [string],
  'host' : PlayerId,
  'time' : [] | [string],
  'creationTime' : Time,
  'sessionId' : SessionId,
  'courts' : bigint,
}
export interface SessionCreationResult {
  'state' : SessionState,
  'sessionId' : SessionId,
  'config' : SessionConfig,
}
export type SessionId = string;
export interface SessionState {
  'assignments' : Array<CourtAssignment>,
  'isCompleted' : boolean,
  'previousWaitlist' : Array<PlayerId>,
  'currentRound' : bigint,
  'waitlist' : Array<PlayerId>,
  'matches' : Array<MatchResult>,
  'players' : Array<PlayerId>,
  'allGamesAssignments' : Array<AllGamesRoundAssignments>,
  'config' : SessionConfig,
}
export type SessionType = { 'randomAllotment' : null } |
  { 'kingQueenOfTheCourt' : null } |
  { 'roundRobin' : null } |
  { 'ladderLeague' : null };
export type Time = bigint;
export interface UserProfile {
  'bio' : [] | [string],
  'name' : string,
  'mobileNumber' : string,
  'workField' : [] | [string],
  'profilePicture' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPlayerToSession' : ActorMethod<
    [SessionId, string, string, [] | [string], [] | [string], [] | [string]],
    undefined
  >,
  'allocatePlayers' : ActorMethod<[SessionId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPlayerProfile' : ActorMethod<[string], PlayerId>,
  'createSession' : ActorMethod<
    [
      bigint,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [bigint],
      GameCode,
      SessionType,
      boolean,
    ],
    SessionCreationResult
  >,
  'endGame' : ActorMethod<[SessionId], undefined>,
  'endRound' : ActorMethod<[SessionId], undefined>,
  'getAllGames' : ActorMethod<
    [SessionId, bigint, bigint],
    Array<AllGamesRoundAssignments>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getSessionGameInfo' : ActorMethod<
    [SessionId],
    [string, [] | [string], [] | [string], [] | [string], [] | [bigint]]
  >,
  'getSessionState' : ActorMethod<[SessionId], SessionState>,
  'getSessionStateByCode' : ActorMethod<[string], SessionState>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinSession' : ActorMethod<[SessionId], undefined>,
  'joinSessionByCode' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitMatchResult' : ActorMethod<[SessionId, Court, GameOutcome], MatchId>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];